export type APIResponseType =
	| "unknown"
	| "fields_missing"
	| "user_registered"
	| "user_already_exists"
	| "user_logged_in"
	| "user_refreshed"
	| "token_theft"
	| "not_authenticated"
	| "user_not_exists"
	| "profile_not_exists"
    | "friend_request_already_sent"
    | "friend_request_accepted"
    | "friend_request_sent"
    | "friends_already";
